-- ATENÇÃO: PARA ESTA VERSÃO DO JOGO (SUPABASE REALTIME BROADCAST), 
-- VOCÊ NÃO PRECISA CRIAR TABELAS NO BANCO DE DADOS!
-- O JOGO USA O MODO "BROADCAST" E "PRESENCE", QUE FUNCIONAM EM MEMÓRIA NO SUPABASE.

-- NO ENTANTO, PARA QUE AS MENSAGENS REALTIME FUNCIONEM,
-- VOCÊ SÓ PRECISA VERIFICAR SE O REALTIME ESTÁ ATIVADO NO SEU PAINEL:

-- 1. Vá em 'Database' -> 'Replication' no menu lateral do Supabase.
-- 2. Vá em 'Tables and Publications'.
-- 3. Verifique se a publicação 'supabase_realtime' existe.

-- CASO VOCÊ QUEIRA NO FUTURO SALVAR O HISTÓRICO DAS PARTIDAS,
-- ABAIXO ESTÁ UM EXEMPLO DE TABELAS QUE PODERIAM SER USADAS:

/*
CREATE TABLE salas (
  id TEXT PRIMARY KEY, -- O código de 4 dígitos
  created_at TIMESTAMPTZ DEFAULT NOW(),
  host_id UUID NOT NULL
);

CREATE TABLE jogadores (
  id UUID PRIMARY KEY,
  sala_id TEXT REFERENCES salas(id) ON DELETE CASCADE,
  nome TEXT NOT NULL,
  last_seen TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE votos (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  sala_id TEXT REFERENCES salas(id) ON DELETE CASCADE,
  quem_votou UUID NOT NULL,
  voto_em TEXT NOT NULL,
  pergunta_texto TEXT NOT NULL,
  created_at TIMESTAMPTZ DEFAULT NOW()
);
*/

-- O script atual ignora essas tabelas e usa comunicação direta entre navegadores.
-- Basta você usar a URL e a ANON KEY que o jogo já vai sincronizar!

-- Inserir as perguntas (Lista Completa com as 20 novas)
insert into questions (category, text) values
('Lealdade e Ética', 'Quem aqui seria o primeiro a aceitar 1 milhão de reais pra nunca mais olhar na cara de ninguém dessa sala?'),
('Lealdade e Ética', 'Se alguém aqui fizesse uma cagada federal por acidente, quem seria a última pessoa que você chamaria pra te ajudar a sumir com as provas?'),
('Lealdade e Ética', 'Quem aqui tá escondendo um segredo que, se vazasse, acabaria com a moral de outra pessoa que tá na roda?'),
('Lealdade e Ética', 'Quem aqui seria o primeiro a te vender por um VIP num show ou camarote de festa?'),
('Lealdade e Ética', 'Se um amigo aqui fosse preso injustamente, quem seria o primeiro a sumir pra não ter que depor a favor?'),
('Lealdade e Ética', 'Quem daqui você tem certeza que já falou mal de você pelas costas pra alguém que está nessa roda?'),
('Lealdade e Ética', 'Quem aqui pegaria o ex de um amigo sem pensar duas vezes se tivesse a chance?'),
('Máscaras Sociais', 'Quem aqui paga de santo e ético, mas na vida real é bem mais babaca do que aparenta?'),
('Máscaras Sociais', 'Quem é a pessoa que mais julga, em silêncio, as escolhas de vida merda que os amigos aqui fazem?'),
('Máscaras Sociais', 'Se o histórico do navegador de todo mundo fosse exposto, quem aqui teria que mudar de país pra não morrer de vergonha da família?'),
('Máscaras Sociais', 'Quem aqui é a pessoa que mais força simpatia nas redes sociais só pra ganhar biscoito?'),
('Máscaras Sociais', 'Quem nesta roda finge ter dinheiro e uma vida foda, mas tá todo endividado no Serasa?'),
('Máscaras Sociais', 'Quem aqui é o ''amigo de todo mundo'' mas na verdade não gosta de quase ninguém que está aqui?'),
('Máscaras Sociais', 'Quem aqui tem a cara de pau de pedir dinheiro emprestado e depois postar foto no rolê caro?'),
('Máscaras Sociais', 'Se a gente pudesse ouvir os pensamentos, quem daqui seria cancelado pela internet em menos de 10 minutos?'),
('Sobrevivência', 'Se o mundo acabasse e só tivesse comida pra um, quem aqui seria o primeiro a trair o grupo pra salvar a própria pele?'),
('Sobrevivência', 'Quem daqui é a pessoa mais fria e calculista quando o assunto é passar por cima dos outros pra conseguir o que quer?'),
('Sobrevivência', 'Num apocalipse zumbi, quem aqui seria o primeiro a empurrar um amigo pra cima dos monstros pra conseguir fugir?'),
('Sobrevivência', 'Quem aqui seria capaz de namorar alguém só por interesse financeiro ou pra subir na vida?'),
('Sobrevivência', 'Se caíssemos em uma ilha deserta, quem seria a primeira pessoa que o grupo decidiria comer (canibalismo) pra não morrer de fome?'),
('Sobrevivência', 'Quem aqui é o maior ''puxa-saco'' de chefe ou de gente poderosa pra conseguir vantagem?'),
('Sobrevivência', 'Quem nesta roda seria o primeiro a aceitar um suborno pra ferrar com a vida de um desconhecido?'),
('Sobrevivência', 'Se víssemos uma mala de dinheiro na rua cheia de sangue, quem aqui pegaria e não contaria pra ninguém?'),
('Relacionamentos', 'Quem aqui é o mestre em fazer gaslighting e deixar o parceiro se sentindo um lixo?'),
('Relacionamentos', 'Quem daqui guarda foto de ex e ainda stalkeia todo santo dia em conta fake?'),
('Relacionamentos', 'Quem aqui terminaria um namoro de anos por mensagem no WhatsApp porque tem medo de conversa séria?'),
('Relacionamentos', 'Quem é a pessoa que mais tem cara de que já foi amante de alguém casado nesta roda?'),
('Relacionamentos', 'Quem aqui é o ''talarico'' que sempre acha a pessoa que o amigo gosta mais interessante?');
